<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add User</name>
   <tag></tag>
   <elementGuidId>aba044d9-5379-43e6-9d9c-949bd6b2296e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Grid_User1_add</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='Grid_User1_add']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a0b11eb0-0d9b-45f5-a346-456ebec2d367</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>e-tbar-btn e-tbtn-txt e-control e-btn e-lib</value>
      <webElementGuid>e81f151b-681f-4c65-8735-efd9fb9aa5c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>24be740b-fa8c-4faf-8e17-f5f53bd531ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Grid_User1_add</value>
      <webElementGuid>98f7acb7-38e0-4168-a1a8-a9f436fb8fcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>5352c086-b4a7-42c7-a036-86637008a30f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Add User</value>
      <webElementGuid>5eaae9f6-281e-4ad3-8fe3-227f5754dc0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add User</value>
      <webElementGuid>d29f71a1-26cf-48da-b737-da8287c8d500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Grid_User1_add&quot;)</value>
      <webElementGuid>db9e61df-1814-41e7-8962-e55e80b0a213</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='Grid_User1_add']</value>
      <webElementGuid>f889bcbf-239d-4dc1-973d-fcb58b225124</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hscroll_3']/div[2]/div/div/div[6]/button</value>
      <webElementGuid>35decc67-65a6-4f3e-b151-c78b11ada70d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Group'])[1]/following::button[1]</value>
      <webElementGuid>ef56fc9b-2fb4-487b-af65-f2bca07c44cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear Filter'])[1]/following::button[2]</value>
      <webElementGuid>59edc387-91b6-4b76-aa53-5600a6920b2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/preceding::button[1]</value>
      <webElementGuid>798e7904-26c1-4f08-8aa1-1966e6c98aa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/button</value>
      <webElementGuid>97c44beb-9063-414e-add3-3f4861a9ffba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'Grid_User1_add' and (text() = 'Add User' or . = 'Add User')]</value>
      <webElementGuid>311cee68-e0a1-4edc-8d80-bd4413016e5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
