<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last Name_PASSWORD</name>
   <tag></tag>
   <elementGuidId>6697aadc-7533-44a0-a98a-7378e6712f06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Grid_User1PASSWORD</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Grid_User1PASSWORD']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>151af176-7527-4a4d-bf68-b1256cc89505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>e-field e-defaultcell</value>
      <webElementGuid>309183b2-f347-4188-a70a-c97277e01736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>808bc7d0-fb29-4b3f-a05a-65c89e93a6e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Grid_User1PASSWORD</value>
      <webElementGuid>2a4cf23f-0c6b-4509-b955-796857cff478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PASSWORD</value>
      <webElementGuid>3f186c25-5113-42ec-9030-2c2726372eb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>e-mappinguid</name>
      <type>Main</type>
      <value>grid-column12</value>
      <webElementGuid>b155a066-ddcc-4e76-8a0e-83d088336144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>514796cd-f3e9-4990-a2c0-d60c7c19e9d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Grid_User1PASSWORD&quot;)</value>
      <webElementGuid>5bd5720f-ea48-4fa4-bd20-c9bb352eac17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Grid_User1PASSWORD']</value>
      <webElementGuid>dfb27ee8-2932-4c87-9d28-0f053ca79ead</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='Grid_User1EditForm']/table/tbody/tr[5]/td/div/input</value>
      <webElementGuid>ab6004d0-c3cf-49d6-8d95-c017700a50ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/table/tbody/tr[5]/td/div/input</value>
      <webElementGuid>e4077e59-8322-43db-9e3f-6624a4ec2742</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'Grid_User1PASSWORD' and @name = 'PASSWORD']</value>
      <webElementGuid>2ba2b684-11c1-4b07-a9fa-5abe4ffc8f92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
