<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_CONFIRMPASSWORD</name>
   <tag></tag>
   <elementGuidId>04804f4c-a235-4f76-81f1-2e1449f46a1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Grid_User1CONFIRMPASSWORD</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Grid_User1CONFIRMPASSWORD']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8eecb8fc-8604-4354-9c3d-6d1700a3c5b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>e-field e-defaultcell e-error</value>
      <webElementGuid>3a18a8ad-4e5b-4bbf-bf09-69e74e237478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>8c4454ce-33aa-4a17-bf8a-0f22d8ba5fb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Grid_User1CONFIRMPASSWORD</value>
      <webElementGuid>36e86136-64a2-416c-9d10-df80e902ad28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CONFIRMPASSWORD</value>
      <webElementGuid>77788d0d-d4e4-4a32-b1bb-b1017e8aaa82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>e-mappinguid</name>
      <type>Main</type>
      <value>grid-column40</value>
      <webElementGuid>83645b4d-19fb-434a-89d7-c7f00c0831bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f575e0f7-33cb-48c5-a949-00ff201563d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6b5d0b87-7579-424a-b25b-66a0025f52dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>Grid_User1CONFIRMPASSWORD-info</value>
      <webElementGuid>4122f22b-c7b2-48fe-975f-e69b4c289145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>33caa04c-a15e-49c4-ac2b-7d3bb0929308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Grid_User1CONFIRMPASSWORD&quot;)</value>
      <webElementGuid>53a7e7b1-46dd-423a-8081-391d832593b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Grid_User1CONFIRMPASSWORD']</value>
      <webElementGuid>1398e9fd-5d7e-4d8f-bdb3-4e880bc89296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='Grid_User1EditForm']/table/tbody/tr[6]/td/div/input</value>
      <webElementGuid>7e84bb4e-11e4-4f1f-aae9-ad85d94e4b3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/table/tbody/tr[6]/td/div/input</value>
      <webElementGuid>dd8157be-de1e-456a-8395-d1667c429aca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'Grid_User1CONFIRMPASSWORD' and @name = 'CONFIRMPASSWORD']</value>
      <webElementGuid>69a9c296-2461-4855-8433-a6d8a9f8f792</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
