<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username_USERID</name>
   <tag></tag>
   <elementGuidId>35eab423-adbb-4657-bb6d-b0447e432fa2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Grid_User1USERID</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Grid_User1USERID']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2cb95713-7f5a-43cd-89a4-dd2a776e47aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>e-field e-defaultcell e-control e-textbox e-lib</value>
      <webElementGuid>9ba95d75-b3d0-47e3-9379-7c2701fc77ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>785fbf1c-b804-4fcf-aa33-55c0231922a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Grid_User1USERID</value>
      <webElementGuid>512daead-21c1-4c5d-8d83-73c136188de1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>USERID</value>
      <webElementGuid>56ece810-2bf6-4483-89f8-f1d06f5d3a17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>e-mappinguid</name>
      <type>Main</type>
      <value>grid-column4</value>
      <webElementGuid>9795e441-01fb-4e19-b87d-e39d7084c730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>fac78976-3660-464a-b454-79932e02495f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>label_Grid_User1USERID</value>
      <webElementGuid>3b18ac7a-7d76-4ccc-9727-ee0a97b258d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Grid_User1USERID&quot;)</value>
      <webElementGuid>a242da7a-f2a6-4534-9090-b8a95320dbe5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Grid_User1USERID']</value>
      <webElementGuid>c140838b-f339-494e-8ab4-b95524db81c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='Grid_User1EditForm']/table/tbody/tr[2]/td/div/input</value>
      <webElementGuid>d22c1b2d-f1d4-4b7a-acb8-657f968f291c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/table/tbody/tr[2]/td/div/input</value>
      <webElementGuid>b07accf3-24b8-4423-b435-b7f5b2d29ef9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Grid_User1USERID' and @name = 'USERID']</value>
      <webElementGuid>49acbae6-f5d2-4d91-82cd-470c75af454a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
