<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Add New User_USERNAME</name>
   <tag></tag>
   <elementGuidId>dd55c19c-0f4c-4ccb-96c3-6e48df1847c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Grid_User1USERNAME</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Grid_User1USERNAME']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2fb21bfa-50be-4e24-8658-1ab52efc43e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>e-field e-defaultcell e-control e-textbox e-lib e-error</value>
      <webElementGuid>dedd38f6-9e1f-4b1a-96ea-f6b287b5014b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>855d1371-e7a6-44d5-abd6-84427cfecbbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Grid_User1USERNAME</value>
      <webElementGuid>e169b519-5e06-42b5-b836-9854fad1bc8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>USERNAME</value>
      <webElementGuid>8dc6ab8e-a670-429d-8885-8c866e722b41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>e-mappinguid</name>
      <type>Main</type>
      <value>grid-column2</value>
      <webElementGuid>b0497c3f-c28c-4f62-9e5f-f97cc123e9c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>657abfd6-b983-42fa-83ff-09f34ecae16a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>label_Grid_User1USERNAME</value>
      <webElementGuid>b20d6819-c8ec-4283-b5d7-81d4dcdd69cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2b22c15e-4eae-41ce-bc71-bcee8186c657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>Grid_User1USERNAME-info</value>
      <webElementGuid>bae7eaf6-3702-40b4-a1dc-fb95b84b1db1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>18932673-9a3e-499d-819d-9ecb6550c9d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Grid_User1USERNAME&quot;)</value>
      <webElementGuid>60b7790d-d80c-4553-9de8-fe4834930014</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Grid_User1USERNAME']</value>
      <webElementGuid>25e777e7-3a2a-4f0f-a425-6bc301357f06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='Grid_User1EditForm']/table/tbody/tr/td/div/input</value>
      <webElementGuid>deb9a8ba-b34b-4f9b-a859-e268322f0095</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/table/tbody/tr/td/div/input</value>
      <webElementGuid>4c4d8ceb-3639-4256-b818-e868ede9cc53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Grid_User1USERNAME' and @name = 'USERNAME']</value>
      <webElementGuid>61bfdb42-f24e-4aae-b2d2-98333d374728</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
