<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_User ID_FIRSTNAME</name>
   <tag></tag>
   <elementGuidId>af3cbe04-d17a-4b32-b884-815d344b5589</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Grid_User1FIRSTNAME</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Grid_User1FIRSTNAME']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eabcc298-80b8-4389-bdb2-6eba8b8b95f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>e-field e-defaultcell e-control e-textbox e-lib</value>
      <webElementGuid>9f7e377b-ee09-413e-8414-baff72c8680e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f68a8d7d-188f-45e5-a0df-aedef9f3857c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Grid_User1FIRSTNAME</value>
      <webElementGuid>ef842400-4a4f-491b-afc8-ad88b8ae40c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FIRSTNAME</value>
      <webElementGuid>042b623b-07c9-4747-9ba7-36078f1f7960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>e-mappinguid</name>
      <type>Main</type>
      <value>grid-column8</value>
      <webElementGuid>89562386-870c-40ea-9f20-6b644cabd6a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>0e1bc45f-7fad-46d8-9155-c7c36b93e89d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>label_Grid_User1FIRSTNAME</value>
      <webElementGuid>188262f7-9446-42a3-b868-7df17476944e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Grid_User1FIRSTNAME&quot;)</value>
      <webElementGuid>d06642b9-b0f4-4eba-bc0e-e8122c63953d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Grid_User1FIRSTNAME']</value>
      <webElementGuid>fb57e0cd-a7c8-4501-b2b6-a4f8af860bde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='Grid_User1EditForm']/table/tbody/tr[3]/td/div/input</value>
      <webElementGuid>b4079679-8c48-4a47-a783-00a3838d6e1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/table/tbody/tr[3]/td/div/input</value>
      <webElementGuid>5a5e6098-7958-4e24-af2b-c9002afe70e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Grid_User1FIRSTNAME' and @name = 'FIRSTNAME']</value>
      <webElementGuid>614d0693-3ddc-4381-8f40-4d7a79cd4b12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
