<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Summary</name>
   <tag></tag>
   <elementGuidId>5bff8bac-c0ca-40e5-8ec1-2fb621de94bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.e-list-item.e-level-2.e-hover > div.e-text-content</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='breadcrumb_active']/ul/li/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;breadcrumb_active&quot;]</value>
      <webElementGuid>d60d7ace-82c5-479a-a03d-980f75b0477b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='breadcrumb_active']/ul/li/div[2]</value>
      <webElementGuid>debd8473-4172-4fe2-b622-5611e9b432c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::div[7]</value>
      <webElementGuid>cce3815f-205a-4d50-afda-9a9ebf61e5d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='admin'])[2]/following::div[13]</value>
      <webElementGuid>69749d7f-014e-4148-ad9e-f515036dac85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operator Labor Overview'])[1]/preceding::div[5]</value>
      <webElementGuid>cdb1b84d-3488-4409-aeb2-084bf6a2c693</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li/div[2]</value>
      <webElementGuid>8eeb66a3-8eae-4577-9886-8671c8d0f142</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Summary' or . = 'Summary')]</value>
      <webElementGuid>d6c1381b-dfd9-43e5-98b2-9b2c14106a89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
