<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_SMD_fas fa-bars</name>
   <tag></tag>
   <elementGuidId>8069a247-da00-44cf-ba5f-aa68760fce50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fas.fa-bars</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>246e82e4-6dca-479b-86f6-d35cdeb1bc35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-bars</value>
      <webElementGuid>acf22208-0686-438a-9916-ff3474bbb266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/nav[@class=&quot;navbar navbar-expand-lg navbar-light fixed-top&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;menu-btn&quot;]/i[@class=&quot;fas fa-bars&quot;]</value>
      <webElementGuid>d7eb0e03-ceb0-4153-adb9-bb2371cba3ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>54bbf2c0-78a7-4db3-bac4-37f316c46dae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
