<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Almasons Consulting LLC_USERNAME</name>
   <tag></tag>
   <elementGuidId>aa6a9cf0-e01f-4a26-82a3-676dc30df3e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='USERNAME']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#USERNAME</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8a7441a7-36f3-4da1-bf89-e6f1f73ae0e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>USERNAME</value>
      <webElementGuid>60f95000-ca0e-444a-a13a-daebe4cf7802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>e-control e-textbox e-lib e-input</value>
      <webElementGuid>49cd1a04-7ed7-4b9f-a1cf-aec458ff641a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ce00bf77-f3a5-4638-8308-1d4386b1ffbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>0d7a2bea-eb5e-4ee7-8704-b7e98a986a48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>USERNAME</value>
      <webElementGuid>88c4ca12-129a-4376-aa83-b100110b50cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>1f369b53-39e4-4867-adf9-adb7d4309c0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-placeholder</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>7a95bd24-92df-4c44-9558-91d5b17bf644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;USERNAME&quot;)</value>
      <webElementGuid>93efe6de-0b62-4edc-acbb-b20f0d13d343</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='USERNAME']</value>
      <webElementGuid>f14abba9-ec10-4eba-952c-9cfc6fc21bd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/input</value>
      <webElementGuid>7dc13c14-25d8-48b7-b112-7e3582038620</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'USERNAME' and @type = 'text' and @name = 'USERNAME' and @placeholder = 'Username']</value>
      <webElementGuid>d7dab006-8f3e-487b-aa27-bc1b7407f67b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
