<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Almasons Consulting LLC_CLIENTID</name>
   <tag></tag>
   <elementGuidId>6f4604c1-1871-4ac7-8265-f4543ca1a2ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CLIENTID']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CLIENTID</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>75b9f6f4-4126-45d2-b8eb-d52cdd993680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CLIENTID</value>
      <webElementGuid>3282f357-8555-4812-8e38-6f2129afb849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>e-control e-textbox e-lib e-input</value>
      <webElementGuid>50e17ca0-58a2-4fe7-b7d8-81f0d50b2974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>592e7bf7-80ad-488e-bcf8-a2bed030b5c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>7fb6d641-e00e-4f08-aa1b-cc545a6f8293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CLIENTID</value>
      <webElementGuid>a5ed3a9f-4a29-4197-a004-ba13723d6b1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Client ID</value>
      <webElementGuid>b32d93ff-6e33-433d-805b-d29b06393e93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-placeholder</name>
      <type>Main</type>
      <value>Client ID</value>
      <webElementGuid>5bc5b368-ef9c-4da5-8610-a51d59316780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CLIENTID&quot;)</value>
      <webElementGuid>d6756cba-4991-4433-8465-e76cadc59fc6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CLIENTID']</value>
      <webElementGuid>57e8b174-fbbb-4af9-a5c1-6c8199566b67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>894e9aa0-1367-4324-98a9-2555859e001a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'CLIENTID' and @type = 'text' and @name = 'CLIENTID' and @placeholder = 'Client ID']</value>
      <webElementGuid>4e3bbe8b-cc15-4cd5-bd09-06471d30dbe6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
