<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Columns</name>
   <tag></tag>
   <elementGuidId>55ef4114-6446-4786-a874-b02abe00fe9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Grid_AssignmentOverview_columnchooser > span.e-tbar-btn-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='Grid_AssignmentOverview_columnchooser']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3681e032-e9de-4acc-8d8b-398c768febbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>e-tbar-btn-text</value>
      <webElementGuid>088d79fa-ac53-45c6-ba61-835b1b51b16f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Columns</value>
      <webElementGuid>c9d83bbf-2cb9-4c07-a95d-1559e23caa4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Grid_AssignmentOverview_columnchooser&quot;)/span[@class=&quot;e-tbar-btn-text&quot;]</value>
      <webElementGuid>c86c5509-401c-4b50-a78d-26ac09d13124</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='Grid_AssignmentOverview_columnchooser']/span</value>
      <webElementGuid>2e41e0b3-ba10-414a-a005-27309433eb7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Excel Export'])[1]/following::span[1]</value>
      <webElementGuid>9db98e31-858c-4263-a9af-96ffba32b0e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PDF Export'])[1]/following::span[3]</value>
      <webElementGuid>a03a21cd-02ff-44dc-a664-15a0d4a719a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Region'])[2]/preceding::span[2]</value>
      <webElementGuid>9d95435a-5d98-4acd-97e6-838a2a6155dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New'])[1]/preceding::span[3]</value>
      <webElementGuid>da0d1999-8169-4d0d-acb7-1823838e7713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Columns']/parent::*</value>
      <webElementGuid>e44fbb20-c7cb-4ccd-a542-32dd58a16d0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button/span</value>
      <webElementGuid>74e4e5aa-58f4-408a-ab63-018b2c8e055d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Columns' or . = 'Columns')]</value>
      <webElementGuid>95aa77f3-6b4f-4e1c-a70d-d7cb7889fd33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
