<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>swipe right</name>
   <tag></tag>
   <elementGuidId>94e98e6f-cee1-417f-abe3-0f5c23f3df3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.e-nav-right-arrow.e-nav-arrow.e-icons</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hscroll_8_nav_right']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f74b727c-732a-4d93-93aa-58c6a02ec71b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>e-nav-right-arrow e-nav-arrow e-icons</value>
      <webElementGuid>276116b0-268c-4c69-980b-52b238feecc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hscroll_8_nav_right&quot;)/div[@class=&quot;e-nav-right-arrow e-nav-arrow e-icons&quot;]</value>
      <webElementGuid>9be0941c-5d34-4670-a305-92661e2a3168</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hscroll_8_nav_right']/div</value>
      <webElementGuid>c02738b1-6504-4ea2-bee7-3c7110fd70bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[3]/div</value>
      <webElementGuid>f280d692-6137-4948-a564-747d93bc2096</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
