<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Summary</name>
   <tag></tag>
   <elementGuidId>52e9f47a-c319-4a00-a1c4-51be767d2e67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.e-list-item.e-level-2.e-hover > div.e-text-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='breadcrumb_active']/ul/li/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e43552f9-1d3e-4f3e-92bc-f70ba07bb9a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>e-text-content</value>
      <webElementGuid>b72f7df2-fa27-4f15-8276-8dcfafbe17fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Summary</value>
      <webElementGuid>1f617e7f-0aa1-4a05-b35e-75ff7aff6a91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;breadcrumb_active&quot;)/ul[@class=&quot;e-list-parent e-ul&quot;]/li[@class=&quot;e-list-item e-level-2 e-hover&quot;]/div[@class=&quot;e-text-content&quot;]</value>
      <webElementGuid>17acc5f4-6e50-436f-81d0-897147ec91f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='breadcrumb_active']/ul/li/div[2]</value>
      <webElementGuid>09ce8267-9c88-47d4-8d19-d82fcb4e45ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::div[7]</value>
      <webElementGuid>e300436d-4d2e-4e51-820d-59c4ceb49dab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='admin'])[2]/following::div[13]</value>
      <webElementGuid>f3c13006-d121-44fc-8910-bad47600bd0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operator Labor Overview'])[1]/preceding::div[5]</value>
      <webElementGuid>d0ad25ba-800a-41d4-b017-c9d226281cf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li/div[2]</value>
      <webElementGuid>0fa4d1fa-c7ac-454a-93ee-0bd5758055b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Summary' or . = 'Summary')]</value>
      <webElementGuid>c1c1f74a-3260-4e14-a9ba-01df7e23c86a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
